language: python

cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download
env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/test_dir/
    - MODULE=hSBM
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="2.7"
      NUMPY_VERSION="1.14.0" SCIPY_VERSION="1.0.0" CYTHON_VERSION="0.21" SKLEARN_VERSION="0.19.1"
    - DISTRIB="conda" PYTHON_VERSION="3.6.4" COVERAGE="true"
      NUMPY_VERSION="1.14.0" SCIPY_VERSION="1.0.0" CYTHON_VERSION="0.21" SKLEARN_VERSION="0.19.1"

install: source ci_scripts/travis/install.sh
script: bash ci_scripts/travis/test.sh
after_success: source ci_scripts/travis/success.sh
